#!/bin/sh

# configure monitor
[ -x "$XDG_CONFIG_HOME/xrandr/layout.sh" ] && "$XDG_CONFIG_HOME/xrandr/layout.sh" || xrandr --auto

# load resources
sysresources="/etc/X11/xinit/.Xresources"
sysmodmap="/etc/X11/xinit/.Xmodmap"
userresources="$XDG_CONFIG_HOME/X11/xresources"
usermodmap="$XDG_CONFIG_HOME/X11/xmodmap"

[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"

for file in $(find "$userresources" -type f 2> /dev/null)
do xrdb -merge "$file"; done

for file in $(find "$usermodmap" -type f 2> /dev/null)
do xmodmap "$file"; done

# load config scripts
if [ -d /etc/X11/xinit/xinitrc.d ]
then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh
    do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[ -f "$XDG_CONFIG_HOME/X11/xprofile" ] && . "$XDG_CONFIG_HOME/X11/xprofile"

# write $DISPLAY to the file
if [ ! -d "$DISPLAY_DIR" ]
then
    mkdir -p -- "$DISPLAY_DIR"
    chmod 1777 -- "$DISPLAY_DIR"
fi

echo "$DISPLAY" > "$DISPLAY_DIR/$VT"
trap 'rm -f -- "$DISPLAY_DIR/$VT"' EXIT

# run window manager
bspwm

