#!/bin/sh

xrandr --auto
[ -z "$PRIMARY_MONITOR" ] || xrandr --output "$PRIMARY_MONITOR" --primary

xset r rate 500 20
kbd-layout.sh qwerty

userresources="$XDG_CONFIG_HOME/X11/xresources"
usermodmap="$XDG_CONFIG_HOME/X11/xmodmap"
sysresources="/etc/X11/xinit/.Xresources"
sysmodmap="/etc/X11/xinit/.Xmodmap"

[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# load config scripts
if [ -d /etc/X11/xinit/xinitrc.d ]
then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh
    do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[ -f "$XDG_CONFIG_HOME/X11/xprofile" ] && . "$XDG_CONFIG_HOME/X11/xprofile"

echo "$DISPLAY" > "$TTY_DISPLAY_FILE"

exec bspwm

