#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate()
{
    degree="$1"
    tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
        case "$(file -b -i "$file")" in
            image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
            *)           mogrify  -rotate "$degree" "$file" ;;
        esac
    done
}

case "$1" in
    "C-54") # C-c
        xclip -r -in -selection clipboard
        notify-send -t 1000 "Path to the image(s) has been copied to clipboard."
        ;;

    "25") # w
        wallpaper.sh "$(shuf -n 1)" &&
            notify-send -t 1000 "Wallpaper has been set."
        ;;

    "C-59") # comma
        rotate 270
        ;;

    "C-60") # period
        rotate  90
        ;;

    "C-61") # slash
        rotate 180
        ;;
esac

